name: make

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt install gcc-arm-none-eabi python3-freetype python3-numpy
    - name: make
      run: make
    - name: upload
      uses: actions/upload-artifact@v3.1.1
      with:
        path: build/io.elf
